issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:IQ-Solutions/.*"

repositories:
  - nia_theme
  - twigextmodule

claim_pattern:
  workflow_ref: "^IQ-Solutions/(nia-blsa-iq|nia-card|nia-alzheimers-iq|nia-main-iq|nia-ros-iq|nia-pos-iq|nia_theme|nia-alzheimers-chatbot|nia-order-reporting)/.*"

permissions:
  contents: read
  packages: read